# SPDX-License-Identifier: Apache-2.0

# name of the action
name: release

# trigger on push events with `v*` in tag
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

# pipeline to execute
jobs:
  release:
    name: release tagged image
    runs-on: ubuntu-latest
    if: github.repository == 'Cargill/vela-ui'

    permissions:
      actions: write # for actions/cache to write to the cache location
      packages: write # for publishing the docker image to this github repo's packages

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-v3-${{ hashFiles('**/elm.json') }}
          restore-keys: |
            ${{ runner.os }}-elm-v3-
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2-
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-v2-
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"

      # ┌┐ ┬ ┬┬┬  ┌┬┐
      # ├┴┐│ │││   ││
      # └─┘└─┘┴┴─┘─┴┘
      - name: install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: run production build
        run: npm run build:prod

      # ┌┬┐┌─┐┌─┐┬┌─┌─┐┬─┐
      #  │││ ││  ├┴┐├┤ ├┬┘
      # ─┴┘└─┘└─┘┴ ┴└─┘┴└─
      - name: login to ghcr
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/cargill/vela-ui
          tags: |
            # only on push tag, "raw" because {{version}} strips "v" prefix
            # also tags "latest" via the default flavor (latest=auto), excluding pre-releases
            type=semver,pattern={{raw}}

      - name: build and push image
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
